version: '3'

networks:
  image_enhancement:
    driver: bridge

services:
  apiserver:
    image: 'bitnami/redis:latest'
    container_name: apiserver
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - image_enhancement

  aiworker:
    image: rabbitmq:management
    container_name: aiworker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - image_enhancement
      
  # postgres database
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - image_enhancement
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    driver: local